import { $ } from 'bun'
import { hasCommand } from '../../utils'
import { logStep, logInfo, select, input } from '../../utils/ui'
import { promptAndSetKey } from '../../config/keys'
import { OMNIROUTE_DEFAULT_MODEL } from '../../config/omniroute'

export const id = 'hermes-agent'
export const label = 'Hermes Agent + MCP'
export const description = '安装 Hermes CLI 并配置模型、MCP'
export const category = 'agent' as const
export const enabled = true

export async function install(): Promise<void> {
  if (await hasCommand('hermes')) {
    logStep('Hermes 已安装')
  } else {
    logStep('安装 Hermes...')
    await $`npm install -g hermes-agent`.nothrow()
  }

  await configure()
}

export async function configure(): Promise<void> {
  const configDir = `${process.env.HOME || '/root'}/.hermes`
  const configPath = `${configDir}/config.yaml`
  await $`mkdir -p ${configDir}`.nothrow()

  const modelOption = await select({
    message: '选择默认模型',
    options: [
      { value: 'auto', label: 'OmniRoute Auto', hint: '默认' },
      { value: 'auto/coding', label: 'OmniRoute Coding' },
      { value: 'auto/fast', label: 'OmniRoute Fast' },
      { value: 'openai/gpt-4o', label: 'OpenAI GPT-4o' },
      { value: 'custom', label: '自定义' },
    ],
  })

  let model = OMNIROUTE_DEFAULT_MODEL
  if (typeof modelOption === 'string') {
    if (modelOption === 'custom') {
      const c = await input({ message: '输入模型' })
      if (typeof c === 'string' && c.trim()) model = c.trim()
    } else {
      model = modelOption
    }
  }

  const providerOption = await select({
    message: '选择供应商',
    options: [
      { value: 'omniroute', label: 'OmniRoute', hint: '默认' },
      { value: 'deepseek', label: 'DeepSeek', hint: '直连 API' },
      { value: 'openai', label: 'OpenAI' },
      { value: 'custom', label: '自定义' },
    ],
  })

  let provider = 'omniroute'
  if (typeof providerOption === 'string') {
    provider = providerOption
    if (providerOption === 'deepseek') {
      await promptAndSetKey('DEEPSEEK_API_KEY', 'DeepSeek API Key')
    } else if (providerOption === 'openai') {
      await promptAndSetKey('OPENAI_API_KEY', 'OpenAI API Key')
    } else if (providerOption === 'custom') {
      const baseUrl = await input({ message: 'API base URL' })
      const keyName = await input({ message: 'API Key 环境变量名' })
      if (typeof keyName === 'string' && keyName.trim()) {
        await promptAndSetKey(keyName.trim(), keyName.trim())
      }
    }
  }

  // YAML config
  const yamlLines = [
    '# Hermes Agent config — generated by rinbake',
    '',
    `model: ${JSON.stringify(model)}`,
    `provider: ${JSON.stringify(provider)}`,
    '',
    'mcp_servers:',
    '  context7:',
    '    command: npx',
    `    args: ["-y", "@upstash/context7-mcp@latest"]`,
    '  brave-search:',
    '    command: npx',
    `    args: ["-y", "@modelcontextprotocol/server-brave-search"]`,
    `    env:`,
    `      BRAVE_API_KEY: "${process.env.BRAVE_API_KEY || ''}"`,
  ]

  await Bun.write(configPath, yamlLines.join('\n') + '\n')
  logInfo(`Hermes 配置已写入 ${configPath}`)
}

export async function detect(): Promise<boolean> {
  return hasCommand('hermes')
}
